import {
  Burn,
  Freeze,
  Paralysis,
  Poison,
  Sleep,
  Condition,
  ConditionName,
  UnknownEffect,
  Move,
  Pokemon,
} from "../types";
import { calculateMoveImpact } from "./battle";
import { weightedRandomIndex } from "./helper";

export function minmaxMoveDecision(
  pokemonMoves: Move[],
  attacker: Pokemon,
  defender: Pokemon
) {
  const moveProbabilities: { [key: string]: number } = {};
  let totalEffectiveness = 0;

  totalEffectiveness = pokemonMoves.reduce(
    (acc, move) =>
      acc + calculateMoveImpact(move, attacker, defender).damage.value,
    0
  );

  pokemonMoves.forEach((move) => {
    moveProbabilities[move.name] =
      calculateMoveImpact(move, attacker, defender).damage.value /
      totalEffectiveness;
  });

  const moves = Object.keys(moveProbabilities);
  const weights = Object.values(moveProbabilities);

  const chosenMoveIndex = weightedRandomIndex(weights);
  const chosenMoveName = moves[chosenMoveIndex];

  return attacker.moves?.find((move) => move.name === chosenMoveName);
}

export const getConditionEffect = (
  effectString: string,
  effectChance?: number
): Condition => {
  if (isParalyze(effectString))
    return {
      name: ConditionName.PARALYSIS,
      speed: 0.5,
      accuracy: 0.75,
      chanceToHit: effectChance ?? 1,
    } as Paralysis;
  if (isPoison(effectString))
    return {
      name: ConditionName.POISON,
      extraDamage: 1 / 16,
      chanceToHit: effectChance ?? 1,
    } as Poison;
  if (isBurnt(effectString))
    return {
      name: ConditionName.BURN,
      extraDamage: 1 / 16,
      attack: 0.5,
      chanceToHit: effectChance ?? 1,
    } as Burn;
  if (isFrozen(effectString))
    return {
      name: ConditionName.FREEZE,
      chanceToReset: 20,
      chanceToHit: effectChance ?? 1,
    } as Freeze;
  if (isSlept(effectString))
    return {
      name: ConditionName.SLEEP,
      chanceToReset: 20,
      chanceToHit: effectChance ?? 1,
    } as Sleep;
  if (isConfused(effectString))
    return {
      name: ConditionName.CONFUSION,
      chanceToReset: 33.3,
      chanceToHit: effectChance ?? 1,
    };
  return { name: ConditionName.UNKNOWN, chanceToHit: 0 } as UnknownEffect;
};

const paralysisMoveNames = [
  //paralysis
  "thunder-punch",
  "body-slam",
  "stun-spore",
  "thunder-shock",
  "thunderbolt",
  "thunder-wave",
  "thunder",
  "lick",
  "glare",
  "zap-cannon",
  "spark",
  "dragon-breath",
  "bounce",
  "volt-tackle",
  "force-palm",
  "thunder-fang",
  "discharge",
  "bolt-strike",
  "freeze-shock",
  "nuzzle",
  "stoked-sparksurfer",
  "splishy-splash",
  "buzzy-buzz",
];

const poisonMoveNames = [
  "poison-sting",
  "twineedle",
  "poison-powder",
  "toxic",
  "smog",
  "sludge",
  "poison-gas",
  "sludge-bomb",
  "poison-fang",
  "poison-tail",
  "poison-jab",
  "cross-poison",
  "gunk-shot",
  "sludge-wave",
  "toxic-thread",
  "shell-side-arm",
];

const burnMoveNames = [
  "fire-punch",
  "ember",
  "flamethrower",
  "fire-blast",
  "flame-wheel",
  "sacred-fire",
  "heat-wave",
  "will-o-wisp",
  "blaze-kick",
  "flare-blitz",
  "fire-fang",
  "lava-plume",
  "scald",
  "inferno",
  "searing-shot",
  "blue-flare",
  "ice-burn",
  "steam-eruption",
  "sizzly-slide",
  "pyro-ball",
  "burning-jealousy",
  "scorching-sands",
];

const freezeMoveNames = [
  "ice-punch",
  "ice-beam",
  "blizzard",
  "powder-snow",
  "ice-fang",
  "freeze-dry",
  "freezing-glare",
];

const sleepMoveNames = [
  "sing",
  "sleep-powder",
  "hypnosis",
  "lovely-kiss",
  "spore",
  "grass-whistle",
  "dark-void",
  "relic-song",
];

const confusionMoveNames = [
  "supersonic",
  "psybeam",
  "confusion",
  "confuse-ray",
  "dizzy-punch",
  "sweet-kiss",
  "swagger",
  "dynamic-punch",
  "flatter",
  "teeter-dance",
  "signal-beam",
  "water-pulse",
  "rock-climb",
  "chatter",
  "hurricane",
  "strange-steam",
];

const generallyAllowedMoveNames = [
  "pound",
  "karate-chop",
  "double-slap",
  "comet-punch",
  "mega-punch",
  "pay-day",
  "fire-punch",
  "ice-punch",
  "thunder-punch",
  "scratch",
  "vice-grip",
  "guillotine",
  "cut",
  "gust",
  "wing-attack",
  "whirlwind",
  "fly",
  "bind",
  "slam",
  "vine-whip",
  "stomp",
  "double-kick",
  "mega-kick",
  "jump-kick",
  "rolling-kick",
  "sand-attack",
  "headbutt",
  "horn-attack",
  "fury-attack",
  "horn-drill",
  "tackle",
  "body-slam",
  "wrap",
  "take-down",
  "double-edge",
  "poison-sting",
  "twineedle",
  "pin-missile",
  "bite",
  "roar",
  "sing",
  "supersonic",
  "sonic-boom",
  "disable",
  "ember",
  "flamethrower",
  "water-gun",
  "hydro-pump",
  "ice-beam",
  "psybeam",
  "bubble-beam",
  "aurora-beam",
  "hyper-beam",
  "peck",
  "drill-peck",
  "submission",
  "low-kick",
  "seismic-toss",
  "strength",
  "absorb",
  "mega-drain",
  "solar-beam",
  "poison-powder",
  "stun-spore",
  "sleep-powder",
  "dragon-rage",
  "fire-spin",
  "thunder-shock",
  "thunderbolt",
  "thunder-wave",
  "thunder",
  "rock-throw",
  "fissure",
  "dig",
  "toxic",
  "confusion",
  "psychic",
  "hypnosis",
  "quick-attack",
  "rage",
  "night-shade",
  "mimic",
  "screech",
  "smokescreen",
  "confuse-ray",
  "mirror-move",
  "egg-bomb",
  "lick",
  "smog",
  "sludge",
  "bone-club",
  "fire-blast",
  "waterfall",
  "clamp",
  "skull-bash",
  "spike-cannon",
  "constrict",
  "kinesis",
  "high-jump-kick",
  "glare",
  "barrage",
  "leech-life",
  "lovely-kiss",
  "sky-attack",
  "transform",
  "dizzy-punch",
  "spore",
  "psywave",
  "crabhammer",
  "fury-swipes",
  "bonemerang",
  "hyper-fang",
  "tri-attack",
  "super-fang",
  "slash",
  "sketch",
  "triple-kick",
  "thief",
  "spider-web",
  "mind-reader",
  "nightmare",
  "flame-wheel",
  "flail",
  "conversion-2",
  "aeroblast",
  "reversal",
  "spite",
  "mach-punch",
  "scary-face",
  "feint-attack",
  "sweet-kiss",
  "sludge-bomb",
  "mud-slap",
  "octazooka",
  "zap-cannon",
  "foresight",
  "bone-rush",
  "lock-on",
  "giga-drain",
  "charm",
  "rollout",
  "false-swipe",
  "swagger",
  "spark",
  "fury-cutter",
  "steel-wing",
  "mean-look",
  "attract",
  "return",
  "present",
  "frustration",
  "pain-split",
  "sacred-fire",
  "dynamic-punch",
  "megahorn",
  "dragon-breath",
  "encore",
  "pursuit",
  "rapid-spin",
  "iron-tail",
  "metal-claw",
  "vital-throw",
  "hidden-power",
  "cross-chop",
  "crunch",
  "psych-up",
  "extreme-speed",
  "ancient-power",
  "shadow-ball",
  "rock-smash",
  "whirlpool",
  "beat-up",
  "fake-out",
  "spit-up",
  "torment",
  "flatter",
  "will-o-wisp",
  "memento",
  "facade",
  "focus-punch",
  "smelling-salts",
  "nature-power",
  "taunt",
  "trick",
  "role-play",
  "superpower",
  "revenge",
  "brick-break",
  "yawn",
  "knock-off",
  "endeavor",
  "skill-swap",
  "secret-power",
  "dive",
  "arm-thrust",
  "luster-purge",
  "mist-ball",
  "feather-dance",
  "blaze-kick",
  "ice-ball",
  "needle-arm",
  "poison-fang",
  "crush-claw",
  "blast-burn",
  "hydro-cannon",
  "meteor-mash",
  "astonish",
  "weather-ball",
  "fake-tears",
  "overheat",
  "odor-sleuth",
  "rock-tomb",
  "silver-wind",
  "metal-sound",
  "grass-whistle",
  "tickle",
  "signal-beam",
  "shadow-punch",
  "extrasensory",
  "sky-uppercut",
  "sand-tomb",
  "sheer-cold",
  "bullet-seed",
  "aerial-ace",
  "icicle-spear",
  "block",
  "dragon-claw",
  "frenzy-plant",
  "bounce",
  "mud-shot",
  "poison-tail",
  "covet",
  "volt-tackle",
  "magical-leaf",
  "leaf-blade",
  "rock-blast",
  "shock-wave",
  "water-pulse",
  "doom-desire",
  "psycho-boost",
  "miracle-eye",
  "wake-up-slap",
  "hammer-arm",
  "gyro-ball",
  "brine",
  "natural-gift",
  "feint",
  "pluck",
  "u-turn",
  "close-combat",
  "payback",
  "assurance",
  "embargo",
  "fling",
  "psycho-shift",
  "trump-card",
  "wring-out",
  "gastro-acid",
  "power-swap",
  "guard-swap",
  "punishment",
  "last-resort",
  "worry-seed",
  "sucker-punch",
  "heart-swap",
  "flare-blitz",
  "force-palm",
  "aura-sphere",
  "poison-jab",
  "dark-pulse",
  "night-slash",
  "aqua-tail",
  "seed-bomb",
  "air-slash",
  "x-scissor",
  "bug-buzz",
  "dragon-pulse",
  "dragon-rush",
  "power-gem",
  "drain-punch",
  "vacuum-wave",
  "focus-blast",
  "energy-ball",
  "brave-bird",
  "earth-power",
  "switcheroo",
  "giga-impact",
  "bullet-punch",
  "avalanche",
  "ice-shard",
  "shadow-claw",
  "thunder-fang",
  "ice-fang",
  "fire-fang",
  "shadow-sneak",
  "mud-bomb",
  "psycho-cut",
  "zen-headbutt",
  "mirror-shot",
  "flash-cannon",
  "rock-climb",
  "defog",
  "draco-meteor",
  "leaf-storm",
  "power-whip",
  "rock-wrecker",
  "cross-poison",
  "gunk-shot",
  "iron-head",
  "magnet-bomb",
  "stone-edge",
  "grass-knot",
  "chatter",
  "judgment",
  "bug-bite",
  "charge-beam",
  "wood-hammer",
  "aqua-jet",
  "attack-order",
  "head-smash",
  "double-hit",
  "roar-of-time",
  "spacial-rend",
  "crush-grip",
  "magma-storm",
  "seed-flare",
  "ominous-wind",
  "shadow-force",
  "guard-split",
  "power-split",
  "psyshock",
  "venoshock",
  "telekinesis",
  "smack-down",
  "storm-throw",
  "flame-burst",
  "heavy-slam",
  "electro-ball",
  "soak",
  "flame-charge",
  "low-sweep",
  "acid-spray",
  "foul-play",
  "simple-beam",
  "entrainment",
  "after-user",
  "round",
  "echoed-voice",
  "chip-away",
  "clear-smog",
  "stored-power",
  "scald",
  "heal-pulse",
  "hex",
  "sky-drop",
  "circle-throw",
  "quash",
  "acrobatics",
  "reflect-type",
  "retaliate",
  "final-gambit",
  "bestow",
  "inferno",
  "water-pledge",
  "fire-pledge",
  "grass-pledge",
  "volt-switch",
  "frost-breath",
  "dragon-tail",
  "wild-charge",
  "drill-run",
  "dual-chop",
  "heart-stamp",
  "horn-leech",
  "sacred-sword",
  "razor-shell",
  "heat-crash",
  "leaf-tornado",
  "steamroller",
  "night-daze",
  "psystrike",
  "tail-slap",
  "hurricane",
  "head-charge",
  "gear-grind",
  "techno-blast",
  "secret-sword",
  "bolt-strike",
  "blue-flare",
  "fiery-dance",
  "freeze-shock",
  "ice-burn",
  "icicle-crash",
  "v-create",
  "fusion-flare",
  "fusion-bolt",
  "flying-press",
  "belch",
  "fell-stinger",
  "phantom-force",
  "trick-or-treat",
  "noble-roar",
  "forests-curse",
  "freeze-dry",
  "parting-shot",
  "topsy-turvy",
  "draining-kiss",
  "electrify",
  "play-rough",
  "fairy-wind",
  "moonblast",
  "play-nice",
  "confide",
  "steam-eruption",
  "hyperspace-hole",
  "water-shuriken",
  "mystical-fire",
  "eerie-impulse",
  "powder",
  "baby-doll-eyes",
  "nuzzle",
  "hold-back",
  "infestation",
  "power-up-punch",
  "oblivion-wing",
  "light-of-ruin",
  "dragon-ascent",
  "hyperspace-fury",
  "breakneck-blitz--physical",
  "breakneck-blitz--special",
  "all-out-pummeling--physical",
  "all-out-pummeling--special",
  "supersonic-skystrike--physical",
  "supersonic-skystrike--special",
  "acid-downpour--physical",
  "acid-downpour--special",
  "tectonic-rage--physical",
  "tectonic-rage--special",
  "continental-crush--physical",
  "continental-crush--special",
  "savage-spin-out--physical",
  "savage-spin-out--special",
  "never-ending-nightmare--physical",
  "never-ending-nightmare--special",
  "corkscrew-crash--physical",
  "corkscrew-crash--special",
  "inferno-overdrive--physical",
  "inferno-overdrive--special",
  "hydro-vortex--physical",
  "hydro-vortex--special",
  "bloom-doom--physical",
  "bloom-doom--special",
  "gigavolt-havoc--physical",
  "gigavolt-havoc--special",
  "shattered-psyche--physical",
  "shattered-psyche--special",
  "subzero-slammer--physical",
  "subzero-slammer--special",
  "devastating-drake--physical",
  "devastating-drake--special",
  "black-hole-eclipse--physical",
  "black-hole-eclipse--special",
  "twinkle-tackle--physical",
  "twinkle-tackle--special",
  "catastropika",
  "first-impression",
  "spirit-shackle",
  "darkest-lariat",
  "ice-hammer",
  "floral-healing",
  "high-horsepower",
  "strength-sap",
  "solar-blade",
  "leafage",
  "spotlight",
  "toxic-thread",
  "throat-chop",
  "pollen-puff",
  "anchor-shot",
  "lunge",
  "fire-lash",
  "power-trip",
  "burn-up",
  "speed-swap",
  "smart-strike",
  "purify",
  "revelation-dance",
  "trop-kick",
  "instruct",
  "beak-blast",
  "dragon-hammer",
  "sinister-arrow-raid",
  "malicious-moonsault",
  "oceanic-operetta",
  "guardian-of-alola",
  "soul-stealing-7-star-strike",
  "stoked-sparksurfer",
  "pulverizing-pancake",
  "genesis-supernova",
  "fleur-cannon",
  "psychic-fangs",
  "stomping-tantrum",
  "shadow-bone",
  "accelerock",
  "liquidation",
  "prismatic-laser",
  "spectral-thief",
  "sunsteel-strike",
  "moongeist-beam",
  "tearful-look",
  "zing-zap",
  "natures-madness",
  "multi-attack",
  "10-000-000-volt-thunderbolt",
  "plasma-fists",
  "photon-geyser",
  "light-that-burns-the-sky",
  "searing-sunraze-smash",
  "menacing-moonraze-maelstrom",
  "lets-snuggle-forever",
  "splintered-stormshards",
  "zippy-zap",
  "floaty-fall",
  "pika-papow",
  "bouncy-bubble",
  "buzzy-buzz",
  "sizzly-slide",
  "glitzy-glow",
  "baddy-bad",
  "sappy-seed",
  "freezy-frost",
  "sparkly-swirl",
  "veevee-volley",
  "double-iron-bash",
  "dynamax-cannon",
  "snipe-shot",
  "jaw-lock",
  "tar-shot",
  "magic-powder",
  "dragon-darts",
  "octolock",
  "bolt-beak",
  "fishious-rend",
  "body-press",
  "decorate",
  "drum-beating",
  "snap-trap",
  "pyro-ball",
  "behemoth-blade",
  "behemoth-bash",
  "aura-wheel",
  "branch-poke",
  "apple-acid",
  "grav-apple",
  "spirit-break",
  "strange-steam",
  "false-surrender",
  "meteor-assault",
  "eternabeam",
  "steel-beam",
  "expanding-force",
  "steel-roller",
  "scale-shot",
  "meteor-beam",
  "shell-side-arm",
  "grassy-glide",
  "rising-voltage",
  "terrain-pulse",
  "skitter-smack",
  "lash-out",
  "poltergeist",
  "flip-turn",
  "triple-axel",
  "dual-wingbeat",
  "scorching-sands",
  "wicked-blow",
  "surging-strikes",
  "thunder-cage",
  "freezing-glare",
  "thunderous-kick",
  "eerie-spell",
  "dire-claw",
  "psyshield-bash",
  "stone-axe",
  "mystical-power",
  "wave-crash",
  "chloroblast",
  "mountain-gale",
  "headlong-rush",
  "barb-barrage",
  "esper-wing",
  "bitter-malice",
  "triple-arrows",
  "infernal-parade",
  "ceaseless-edge",
  "tera-blast",
  "axe-kick",
  "last-respects",
  "lumina-crash",
  "order-up",
  "jet-punch",
  "spicy-extract",
  "spin-out",
  "population-bomb",
  "ice-spinner",
  "glaive-rush",
  "salt-cure",
  "triple-dive",
  "doodle",
  "kowtow-cleave",
  "flower-trick",
  "torch-song",
  "aqua-step",
  "raging-bull",
  "psyblade",
  "hydro-steam",
  "ruination",
  "collision-course",
  "electro-drift",
  "pounce",
  "trailblaze",
  "chilling-water",
  "hyper-drill",
  "twin-beam",
  "rage-fist",
  "armor-cannon",
  "bitter-blade",
  "double-shock",
  "gigaton-hammer",
  "aqua-cutter",
  "blazing-torque",
  "wicked-torque",
  "noxious-torque",
  "combat-torque",
  "magical-torque",
  "blood-moon",
  "matcha-gotcha",
  "syrup-bomb",
  "ivy-cudgel",
  "electro-shot",
  "fickle-beam",
  "thunderclap",
  "mighty-cleave",
  "tachyon-cutter",
  "hard-press",
  "alluring-voice",
  "temper-flare",
  "supercell-slam",
  "psychic-noise",
  "upper-hand",
  "malignant-chain",
  "shadow-rush",
  "shadow-blast",
  "shadow-blitz",
  "shadow-bolt",
  "shadow-break",
  "shadow-chill",
  "shadow-end",
  "shadow-fire",
];

export const totalAllowedMoveNames = [
  ...new Set([
    ...paralysisMoveNames,
    ...poisonMoveNames,
    ...burnMoveNames,
    ...freezeMoveNames,
    ...sleepMoveNames,
    ...confusionMoveNames,
    ...generallyAllowedMoveNames,
  ]),
];

const isParalyze = (effect: string) =>
  effect.toLowerCase().includes("paralyze");
const isPoison = (effect: string) => effect.toLowerCase().includes("poison");
const isBurnt = (effect: string) => effect.toLowerCase().includes("burn");
const isFrozen = (effect: string) => effect.toLowerCase().includes("freeze");
const isSlept = (effect: string) => effect.toLowerCase().includes("sleep");
const isConfused = (effect: string) => effect.toLowerCase().includes("confus");
export const hasRecoil = (effect: string) =>
  effect.toLowerCase().includes("recoil");
export const hasDrain = (effect: string) =>
  effect.toLowerCase().includes("drain");
